# Generated from docs/openapi.json. DO NOT EDIT.
from __future__ import annotations

from typing import Any, Literal, Optional, Union
from pydantic import BaseModel, ConfigDict, Field, RootModel

class Run(BaseModel):
    model_config = ConfigDict(extra="forbid", populate_by_name=True)
    id: str = Field(...)
    state: str = Field(...)
    version: int = Field(...)
    gateStatus: Optional[str] = Field(default=None)

class ApiError(BaseModel):
    model_config = ConfigDict(extra="forbid", populate_by_name=True)
    error: str = Field(...)
    message: Optional[str] = Field(default=None)
    details: Optional[dict[str, Any]] = Field(default=None)
    requestId: Optional[str] = Field(default=None)

class ArtifactV2(BaseModel):
    model_config = ConfigDict(extra="forbid", populate_by_name=True)
    schemaVersion: Literal["2.0"] = Field(...)
    id: str = Field(...)
    runId: str = Field(...)
    scenarioId: str = Field(...)
    stepId: Optional[str] = Field(default=None)
    attemptId: str = Field(...)
    attempt: int = Field(...)
    kind: Literal["screenshot", "dom", "network", "console", "trace", "video", "download", "operation-log", "report", "attachment", "source-patch", "changed-files-archive", "repair-validation-log"] = Field(...)
    origin: Literal["runtime-captured", "fixture", "simulated", "user-uploaded", "agent-generated", "legacy-unverified"] = Field(...)
    storageUri: str = Field(...)
    replicaUris: Optional[list[str]] = Field(default=[])
    sequence: int = Field(...)
    monotonicOffsetMs: float = Field(...)
    integrity: dict[str, Any] = Field(...)
    locator: Optional[dict[str, Any]] = Field(default={})
    fixtureManifestSha256: Optional[str] = Field(default=None)

class RunEvent(BaseModel):
    model_config = ConfigDict(extra="forbid", populate_by_name=True)
    schemaVersion: Literal["1.0"] = Field(...)
    id: str = Field(...)
    runId: str = Field(...)
    type: Literal["run_created", "plan_generated", "plan_approved", "permission_granted", "run_queued", "run_preparing", "run_started", "run_paused", "run_resumed", "evidence_collecting", "run_judging", "human_review_requested", "decision_overridden", "run_completed", "run_failed", "run_blocked", "run_cancelled"] = Field(...)
    version: int = Field(...)
    createdAt: str = Field(...)
    actor: str = Field(...)
    idempotencyKey: str = Field(...)
    payload: Optional[dict[str, Any]] = Field(default={})

class AgentGraphProjection(BaseModel):
    model_config = ConfigDict(extra="forbid", populate_by_name=True)
    schemaVersion: Literal["1.0"] = Field(...)
    runId: str = Field(...)
    threadId: str = Field(...)
    mode: Literal["shadow", "active"] = Field(...)
    status: Literal["idle", "running", "interrupted", "completed", "failed", "cancelled"] = Field(...)
    currentNode: Optional[Literal["intake", "discover", "build-coverage-map", "plan", "compile", "approve-plan", "prepare-sandbox", "approve-capabilities", "execute", "collect-and-gate", "triage-failure", "selective-judge", "repair", "finalize"]] = Field(default=None)
    completedNodes: Optional[list[Literal["intake", "discover", "build-coverage-map", "plan", "compile", "approve-plan", "prepare-sandbox", "approve-capabilities", "execute", "collect-and-gate", "triage-failure", "selective-judge", "repair", "finalize"]]] = Field(default=[])
    progress: float = Field(...)
    pendingInterrupt: Optional[dict[str, Any]] = Field(default=None)
    lastError: Optional[dict[str, Any]] = Field(default=None)
    tokenUsage: Optional[int] = Field(default=0)
    repairSessionId: Optional[str] = Field(default=None)
    updatedAt: str = Field(...)

class RepairSession(BaseModel):
    model_config = ConfigDict(extra="forbid", populate_by_name=True)
    schemaVersion: Literal["1.0"] = Field(...)
    id: str = Field(...)
    runId: str = Field(...)
    projectId: str = Field(...)
    status: Literal["draft", "analyzing", "editing", "validating", "ready-for-review", "exported", "applied", "failed", "blocked", "cancelled"] = Field(...)
    baseSourceSha256: str = Field(...)
    workspaceRoot: str = Field(...)
    summary: Optional[str] = Field(default="")
    failureClass: Optional[Literal["product-bug", "test-script", "environment", "evidence", "unknown"]] = Field(default="unknown")
    files: Optional[list[dict[str, Any]]] = Field(default=[])
    validation: Optional[dict[str, Any]] = Field(default=None)
    iteration: Optional[int] = Field(default=0)
    maxFiles: Optional[int] = Field(default=20)
    maxChangedLines: Optional[int] = Field(default=2000)
    createdAt: str = Field(...)
    updatedAt: str = Field(...)

class RepairExport(BaseModel):
    model_config = ConfigDict(extra="forbid", populate_by_name=True)
    id: str = Field(...)
    repairSessionId: str = Field(...)
    format: Literal["patch", "zip"] = Field(...)
    artifactId: str = Field(...)
    downloadUrl: str = Field(...)
    sha256: str = Field(...)
    sizeBytes: int = Field(...)
    createdAt: str = Field(...)

class CreateRunRequest(BaseModel):
    model_config = ConfigDict(extra="forbid", populate_by_name=True)
    runId: Optional[str] = Field(default=None)
    runKind: Optional[Literal["parent", "path", "validation"]] = Field(default="parent")
    parentRunId: Optional[str] = Field(default=None)
    coverageItemId: Optional[str] = Field(default=None)
    organizationId: Optional[str] = Field(default="local")
    projectId: Optional[str] = Field(default=None)
    actor: Optional[str] = Field(default="api-user")
    idempotencyKey: str = Field(...)
    input: dict[str, Any] = Field(...)

class CoverageItem(BaseModel):
    model_config = ConfigDict(extra="forbid", populate_by_name=True)
    schemaVersion: Literal["1.0"] = Field(...)
    id: str = Field(...)
    runId: str = Field(...)
    flowId: str = Field(...)
    module: str = Field(...)
    surface: Literal["page", "api", "data", "background-task"] = Field(...)
    route: Optional[str] = Field(default=None)
    operationId: Optional[str] = Field(default=None)
    dataEntity: Optional[str] = Field(default=None)
    risk: Literal["low", "medium", "high", "critical"] = Field(...)
    preconditions: Optional[list[str]] = Field(default=[])
    permissions: Optional[list[str]] = Field(default=[])
    testDataRefs: Optional[list[str]] = Field(default=[])
    actionPathIds: Optional[list[str]] = Field(default=[])
    oracleIds: Optional[list[str]] = Field(default=[])
    requiredEvidenceKinds: Optional[list[Literal["screenshot", "dom", "network", "console", "trace", "video", "download", "operation-log", "report", "attachment", "source-patch", "changed-files-archive", "repair-validation-log"]]] = Field(default=[])
    structuredPlan: Optional[dict[str, Any]] = Field(default=None)
    disposition: Literal["executed", "excluded", "blocked", "pending"] = Field(...)
    dispositionReason: Optional[str] = Field(default=None)
    scenarioId: Optional[str] = Field(default=None)
    attemptId: Optional[str] = Field(default=None)
    childRunId: Optional[str] = Field(default=None)
    createdAt: str = Field(...)
    updatedAt: str = Field(...)

class LlmInvocation(BaseModel):
    model_config = ConfigDict(extra="forbid", populate_by_name=True)
    schemaVersion: Optional[Literal["2.0"]] = Field(default="2.0")
    id: str = Field(...)
    runId: Optional[str] = Field(default=None)
    experimentId: Optional[str] = Field(default=None)
    purpose: Literal["planning", "judging", "triage", "repairing", "assistant"] = Field(...)
    provider: Literal["openai-compatible", "openai", "anthropic", "openrouter", "custom"] = Field(...)
    model: str = Field(...)
    requestedModel: Optional[str] = Field(default=None)
    returnedModel: Optional[str] = Field(default=None)
    modelProfileId: Optional[str] = Field(default=None)
    langChainAdapterVersion: Optional[str] = Field(default=None)
    providerAdapterVersion: Optional[str] = Field(default=None)
    promptTemplateId: Optional[str] = Field(default=None)
    promptVersion: Optional[str] = Field(default=None)
    promptSha256: Optional[str] = Field(default=None)
    inputSummarySha256: Optional[str] = Field(default=None)
    actionDslVersion: Optional[str] = Field(default=None)
    outputSchemaVersion: Optional[str] = Field(default=None)
    graphVersion: Optional[str] = Field(default=None)
    scenarioRegistrySha256: Optional[str] = Field(default=None)
    projectDigest: Optional[str] = Field(default=None)
    routeReason: Optional[str] = Field(default=None)
    ruleCapable: Optional[bool] = Field(default=None)
    ruleBypassReason: Optional[str] = Field(default=None)
    cachePolicy: Optional[Literal["use", "bypass"]] = Field(default="use")
    cacheHit: Optional[bool] = Field(default=False)
    sourceCallId: Optional[str] = Field(default=None)
    requestId: Optional[str] = Field(default=None)
    queuedAt: Optional[str] = Field(default=None)
    startedAt: str = Field(...)
    firstTokenAt: Optional[str] = Field(default=None)
    completedAt: Optional[str] = Field(default=None)
    durationMs: int = Field(...)
    timing: Optional[dict[str, Any]] = Field(default=None)
    status: Literal["passed", "failed", "blocked"] = Field(...)
    usage: Optional[dict[str, Any]] = Field(default={})
    errorCode: Optional[str] = Field(default=None)
    failureClass: Optional[Literal["transport", "authentication", "authorization", "model-access", "budget", "semantic", "provider", "unknown"]] = Field(default=None)
    transportMode: Optional[Literal["stream", "non-stream-fallback"]] = Field(default=None)
    fallbackReason: Optional[str] = Field(default=None)
    fallbackImpact: Optional[Literal["none", "plan-source-changed", "recommendation-unavailable", "human-review-required", "path-blocked"]] = Field(default="none")
    finalStatusImpact: Optional[Literal["none", "advisory-only", "forced-review", "blocked"]] = Field(default="none")
    transportAttempts: Optional[list[dict[str, Any]]] = Field(default=None)
    semanticRepairAttempts: Optional[list[dict[str, Any]]] = Field(default=[])
    redactedInputSummary: Optional[str] = Field(default=None)
    structuredOutput: Optional[dict[str, Any]] = Field(default=None)
    encryptedOutputRef: Optional[str] = Field(default=None)
    knowledgeContextId: Optional[str] = Field(default=None)
    knowledgeDecisionId: Optional[str] = Field(default=None)
    knowledgeToolExecutionIds: Optional[list[str]] = Field(default=[])
    boundaryPolicyVersion: Optional[str] = Field(default=None)
    knowledgeValidationStatus: Optional[Literal["not-applicable", "pending", "verified", "rejected", "expired"]] = Field(default="not-applicable")

class Conclusion(BaseModel):
    model_config = ConfigDict(extra="forbid", populate_by_name=True)
    schemaVersion: Literal["1.0"] = Field(...)
    conclusionId: str = Field(...)
    runId: str = Field(...)
    scenarioId: str = Field(...)
    attemptId: str = Field(...)
    claimType: Literal["assertion", "machine-gate", "judge-finding", "failure-classification", "final-status", "human-override"] = Field(...)
    status: str = Field(...)
    source: Literal["deterministic", "llm-advisory", "human"] = Field(...)
    assertionIds: Optional[list[str]] = Field(default=[])
    evidenceRefs: list[str] = Field(...)
    proofStatus: Literal["verified", "missing", "invalid", "legacy-unverified"] = Field(...)
    createdAt: str = Field(...)
    policyVersion: str = Field(...)
    canonicalSha256: Optional[str] = Field(default=None)
    supersedesConclusionId: Optional[str] = Field(default=None)

class ProofEdge(BaseModel):
    model_config = ConfigDict(extra="forbid", populate_by_name=True)
    schemaVersion: Literal["1.0"] = Field(...)
    id: str = Field(...)
    runId: str = Field(...)
    scenarioId: str = Field(...)
    attemptId: str = Field(...)
    fromType: Literal["conclusion", "assertion", "oracle", "evidence", "artifact", "attempt", "step"] = Field(...)
    fromId: str = Field(...)
    toType: Literal["conclusion", "assertion", "oracle", "evidence", "artifact", "attempt", "step"] = Field(...)
    toId: str = Field(...)
    relation: Literal["supported-by-assertion", "evaluates-oracle", "supported-by-evidence", "materialized-by-artifact", "captured-in-attempt", "produced-by-step", "supersedes"] = Field(...)
    canonicalSha256: Optional[str] = Field(default=None)
    createdAt: str = Field(...)

class KnowledgeClaim(BaseModel):
    model_config = ConfigDict(extra="forbid", populate_by_name=True)
    id: str = Field(...)
    subject: Optional[str] = Field(default=None)
    supersedesClaimId: Optional[str] = Field(default=None)
    statement: str = Field(...)
    status: Literal["observed", "user-provided", "retrieved", "inferred", "assumed", "unknown"] = Field(...)
    domain: Literal["general", "project-static", "runtime", "user-intent", "credential-metadata", "external-documentation"] = Field(...)
    sourceRefs: Optional[list[str]] = Field(default=[])
    confidence: float = Field(...)
    observedAt: Optional[str] = Field(default=None)
    expiresAt: Optional[str] = Field(default=None)
    sensitive: Optional[bool] = Field(default=False)
    scope: Optional[dict[str, Any]] = Field(default={})

class LlmKnowledgeContext(BaseModel):
    model_config = ConfigDict(extra="forbid", populate_by_name=True)
    schemaVersion: Optional[Literal["1.0", "2.0"]] = Field(default="2.0")
    id: Optional[str] = Field(default=None)
    runId: Optional[str] = Field(default=None)
    invocationId: Optional[str] = Field(default=None)
    purpose: Literal["planning", "judging", "triage", "repairing", "assistant"] = Field(...)
    projectSnapshot: Optional[dict[str, Any]] = Field(default=None)
    claims: Optional[list[dict[str, Any]]] = Field(default=[])
    allowedCapabilities: Optional[list[str]] = Field(default=[])
    allowedTools: Optional[list[str]] = Field(default=[])
    unknowns: Optional[list[dict[str, Any]]] = Field(default=[])
    untrustedInputKinds: Optional[list[Literal["requirement", "diff", "source", "dom", "console", "network", "external-document", "prior-model-output"]]] = Field(default=[])
    generatedAt: str = Field(...)

class KnowledgeDecision(BaseModel):
    model_config = ConfigDict(extra="forbid", populate_by_name=True)
    id: str = Field(...)
    runId: Optional[str] = Field(default=None)
    contextId: str = Field(...)
    invocationId: Optional[str] = Field(default=None)
    output: dict[str, Any] = Field(...)
    validationStatus: Literal["pending", "verified", "rejected", "expired"] = Field(...)
    validationErrors: Optional[list[str]] = Field(default=[])
    toolExecutionIds: Optional[list[str]] = Field(default=[])
    canonicalSha256: str = Field(...)
    policyVersion: str = Field(...)
    createdAt: str = Field(...)

class KnowledgeConflict(BaseModel):
    model_config = ConfigDict(extra="forbid", populate_by_name=True)
    id: str = Field(...)
    runId: Optional[str] = Field(default=None)
    contextId: str = Field(...)
    domain: Literal["actual-state", "expected-behavior"] = Field(...)
    claimIds: list[str] = Field(...)
    status: Literal["open", "resolved", "superseded"] = Field(...)
    resolution: Optional[dict[str, Any]] = Field(default=None)
    canonicalSha256: str = Field(...)
    createdAt: str = Field(...)

class KnowledgeToolExecution(BaseModel):
    model_config = ConfigDict(extra="forbid", populate_by_name=True)
    id: str = Field(...)
    runId: Optional[str] = Field(default=None)
    contextId: str = Field(...)
    request: dict[str, Any] = Field(...)
    inputSha256: str = Field(...)
    status: Literal["started", "completed", "failed", "denied"] = Field(...)
    outputClaimIds: Optional[list[str]] = Field(default=[])
    outputClaims: Optional[list[dict[str, Any]]] = Field(default=[])
    outputSummary: Optional[str] = Field(default=None)
    outputData: Optional[Any] = Field(default=None)
    errorCode: Optional[str] = Field(default=None)
    permissionEventId: Optional[str] = Field(default=None)
    startedAt: str = Field(...)
    completedAt: Optional[str] = Field(default=None)

class AgentMessage(BaseModel):
    model_config = ConfigDict(extra="forbid", populate_by_name=True)
    id: str = Field(...)
    runId: str = Field(...)
    role: Literal["user", "assistant", "system", "tool"] = Field(...)
    content: str = Field(...)
    reasoningSummary: Optional[dict[str, Any]] = Field(default=None)
    knowledgeContextId: Optional[str] = Field(default=None)
    knowledgeDecisionId: Optional[str] = Field(default=None)
    llmCallId: Optional[str] = Field(default=None)
    suggestedAction: Optional[str] = Field(default=None)
    requiresConfirmation: Optional[bool] = Field(default=None)
    createdAt: str = Field(...)

for _model in [
    Run,
    ApiError,
    ArtifactV2,
    RunEvent,
    AgentGraphProjection,
    RepairSession,
    RepairExport,
    CreateRunRequest,
    CoverageItem,
    LlmInvocation,
    Conclusion,
    ProofEdge,
    KnowledgeClaim,
    LlmKnowledgeContext,
    KnowledgeDecision,
    KnowledgeConflict,
    KnowledgeToolExecution,
    AgentMessage,
]:
    _model.model_rebuild()

