import { testConnectorEnvelope } from "./connector.test.js";
import {
  testDiscoveryProbeExecutesActionBeforeOracle,
  testDiscoveryObservationBoundsAndRedactsRuntimeFacts,
  testDiscoveryScanAcceptsVisibleStreamingDom,
  testDiscoveryScanDrafts,
  testDiscoveryRecognizesLoginAfterNonFormControls,
  testDiscoveryScanPreservesActiveNetworkAtBudgetBoundary,
  testDiscoveryScanWaitsForProgressingModuleGraph,
  testSmokeFirstDiscoveryOrchestration
} from "./discoveryScan.test.js";
import { testCiCliErrorReports } from "./ciCliErrorReports.test.js";
import { testCiContract } from "./ciContract.test.js";
import { testCiGatePolicy } from "./ciGatePolicy.test.js";
import { testCiShellExitContract } from "./ciShellExit.test.js";
import { testExternalProjectSmoke } from "./externalProjectSmoke.test.js";
import { testGovernanceSecurityBot } from "./governanceSecurityBot.test.js";
import { testArtifactIntegrity } from "./artifactIntegrity.test.js";
import { testJudgeSchema } from "./judgeSchema.test.js";
import { testLocalConfigInit } from "./localConfigInit.test.js";
import { testPlanStepSchema } from "./planStepSchema.test.js";
import { testProjectDetectionWizard } from "./projectDetection.test.js";
import { testProjectAdapter } from "./projectAdapter.test.js";
import { testProjectLoginStore } from "./projectLoginStore.test.js";
import { testReportRendererRedaction } from "./reportRenderer.test.js";
import { testReportsRetention } from "./reportsRetention.test.js";
import { testRunRequestContract } from "./runRequestContract.test.js";
import { testRunBundleArchive } from "./runBundleArchive.test.js";
import { testRunHistoryComparison } from "./runHistory.test.js";
import { testRunLockGovernance } from "./runLock.test.js";
import { testScenarioDraftCannotTrustEmptyMissingInfo, testScenarioDraftLifecycle } from "./scenarioDraft.test.js";
import { testScenarioParser } from "./scenarioParser.test.js";
import { testSecurityBoundaries } from "./security.test.js";
import { testServiceHealthContract } from "./serviceHealth.test.js";
import { testRunnerExecutablePlanBinding, testRunnerLifecyclePolicy } from "./testRunnerLifecycle.test.js";
import { testInvestmentAgentWorkflowExternalSmoke } from "./investmentAgentWorkflowSmoke.test.js";
import { testBenchmarkContract } from "./benchmarkContract.test.js";
import { testBenchmarkEvaluation } from "./benchmark.test.js";
import { testLlmRoutingPolicy } from "./llmRoutingPolicy.test.js";
import { testIndependentFixtures } from "./independentFixtures.test.js";
import { testRepairProposals } from "./repairProposal.test.js";
import { testRepairDecision } from "./repairDecision.test.js";
import { testRepairPlanLedger } from "./repairPlanLedger.test.js";
import { testRunEventStore } from "./runEventStore.test.js";
import { testRetryPolicy } from "./retryPolicy.test.js";
import { testGithubChecks } from "./githubChecks.test.js";
import { testCodeImpactGraph } from "./codeImpactGraph.test.js";
import { testMissionPreview } from "./missionPreview.test.js";
import { testProductionAcceptanceContract } from "./productionAcceptanceContract.test.js";
import { testLlmPlannerFailClosed } from "./llmPlanner.test.js";
import { testEvidenceQuality } from "./evidenceQuality.test.js";
import { testUntrustedInputDefense } from "./untrustedInput.test.js";
import { testRedactionPreservesUsageTelemetry } from "./redaction.test.js";
import { testCompiledPlanExecution } from "./compiledPlanExecution.test.js";
import { testBenchmarkSummary } from "./benchmarkSummary.test.js";
import { testLlmProviderResponsesTransport } from "./llmProvider.test.js";
import { testPlanningConversation } from "./planningConversation.test.js";
import { testProjectFolderBrowser } from "./projectFolderBrowser.test.js";
import { testRepairWorkspace } from "./repairWorkspace.test.js";
import { testProofGraph } from "./proofGraph.test.js";
import { testLlmLifecycle } from "./llmLifecycle.test.js";
import { testStructuredActionExecutors } from "./structuredActionExecutors.test.js";
import { testLlmBudgetLedger } from "./llmBudgetLedger.test.js";
import { testAgentGraphMode } from "./agentGraphMode.test.js";
import { testHumanInLoopInterrupt } from "./humanInLoopInterrupt.test.js";
import { testKnowledgeBoundary } from "./knowledgeBoundary.test.js";
import { testKnowledgeBoundaryPlatform } from "./knowledgeBoundaryPlatform.test.js";
import { testProjectAuthorizationMatrix } from "./projectAuthorization.test.js";
import { testAssistantFallback } from "./assistantFallback.test.js";
import { testProofBundleValidator } from "./proofBundleValidator.test.js";
import { testProofBundleIntegrity } from "./proofBundleIntegrity.test.js";
import { testEvidenceArtifactLinker } from "./evidenceArtifactLinker.test.js";
import { testSustainabilityModules } from "./sustainabilityModules.test.js";

async function main() {
  testAssistantFallback();
  testProofBundleValidator();
  testEvidenceArtifactLinker();
  await testSustainabilityModules();
  testProofBundleIntegrity();
  await testConnectorEnvelope();
  await testProjectDetectionWizard();
  await testProjectFolderBrowser();
  await testRepairWorkspace();
  await testProofGraph();
  testLlmLifecycle();
  await testLlmBudgetLedger();
  testAgentGraphMode();
  await testHumanInLoopInterrupt();
  testKnowledgeBoundary();
  await testKnowledgeBoundaryPlatform();
  await testStructuredActionExecutors();
  await testDiscoveryScanDrafts();
  await testDiscoveryRecognizesLoginAfterNonFormControls();
  await testDiscoveryObservationBoundsAndRedactsRuntimeFacts();
  await testSmokeFirstDiscoveryOrchestration();
  await testDiscoveryProbeExecutesActionBeforeOracle();
  await testDiscoveryScanAcceptsVisibleStreamingDom();
  await testDiscoveryScanWaitsForProgressingModuleGraph();
  await testDiscoveryScanPreservesActiveNetworkAtBudgetBoundary();
  await testGovernanceSecurityBot();
  await testProjectAuthorizationMatrix();
  testCiContract();
  await testCiGatePolicy();
  await testCiCliErrorReports();
  await testCiShellExitContract();
  await testProjectAdapter();
  await testProjectLoginStore();
  await testExternalProjectSmoke();
  await testInvestmentAgentWorkflowExternalSmoke();
  await testBenchmarkContract();
  await testProductionAcceptanceContract();
  await testLlmPlannerFailClosed();
  await testLlmProviderResponsesTransport();
  testPlanningConversation();
  testEvidenceQuality();
  testUntrustedInputDefense();
  testRedactionPreservesUsageTelemetry();
  testBenchmarkEvaluation();
  testBenchmarkSummary();
  testLlmRoutingPolicy();
  await testIndependentFixtures();
  testRepairProposals();
  testRepairDecision();
  await testRepairPlanLedger();
  await testRunEventStore();
  testRetryPolicy();
  testGithubChecks();
  await testCodeImpactGraph();
  testMissionPreview();
  testRunnerLifecyclePolicy();
  testRunnerExecutablePlanBinding();
  await testCompiledPlanExecution();
  await testScenarioDraftLifecycle();
  await testScenarioDraftCannotTrustEmptyMissingInfo();
  testScenarioParser();
  testPlanStepSchema();
  testJudgeSchema();
  testReportRendererRedaction();
  await testSecurityBoundaries();
  await testRunHistoryComparison();
  await testRunLockGovernance();
  await testReportsRetention();
  testRunRequestContract();
  await testArtifactIntegrity();
  await testLocalConfigInit();
  await testServiceHealthContract();
  await testRunBundleArchive();
  await import("../src/selfTest.js");
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
