import { testConnectorEnvelope } from "./connector.test.js";
import { testDiscoveryScanDrafts } from "./discoveryScan.test.js";
import { testCiCliErrorReports } from "./ciCliErrorReports.test.js";
import { testCiContract } from "./ciContract.test.js";
import { testCiGatePolicy } from "./ciGatePolicy.test.js";
import { testCiShellExitContract } from "./ciShellExit.test.js";
import { testExternalProjectSmoke } from "./externalProjectSmoke.test.js";
import { testGovernanceSecurityBot } from "./governanceSecurityBot.test.js";
import { testArtifactIntegrity } from "./artifactIntegrity.test.js";
import { testJudgeSchema } from "./judgeSchema.test.js";
import { testLocalConfigInit } from "./localConfigInit.test.js";
import { testPlanStepSchema } from "./planStepSchema.test.js";
import { testProjectDetectionWizard } from "./projectDetection.test.js";
import { testProjectAdapter } from "./projectAdapter.test.js";
import { testReportRendererRedaction } from "./reportRenderer.test.js";
import { testReportsRetention } from "./reportsRetention.test.js";
import { testRunRequestContract } from "./runRequestContract.test.js";
import { testRunBundleArchive } from "./runBundleArchive.test.js";
import { testRunHistoryComparison } from "./runHistory.test.js";
import { testRunLockGovernance } from "./runLock.test.js";
import { testScenarioDraftLifecycle } from "./scenarioDraft.test.js";
import { testScenarioParser } from "./scenarioParser.test.js";
import { testSecurityBoundaries } from "./security.test.js";
import { testServiceHealthContract } from "./serviceHealth.test.js";
import { testRunnerExecutablePlanBinding, testRunnerLifecyclePolicy } from "./testRunnerLifecycle.test.js";
import { testInvestmentAgentWorkflowExternalSmoke } from "./investmentAgentWorkflowSmoke.test.js";
import { testBenchmarkContract } from "./benchmarkContract.test.js";
import { testBenchmarkEvaluation } from "./benchmark.test.js";
import { testIndependentFixtures } from "./independentFixtures.test.js";
import { testRepairProposals } from "./repairProposal.test.js";
import { testRunEventStore } from "./runEventStore.test.js";
import { testRetryPolicy } from "./retryPolicy.test.js";
import { testGithubChecks } from "./githubChecks.test.js";
import { testCodeImpactGraph } from "./codeImpactGraph.test.js";
import { testMissionPreview } from "./missionPreview.test.js";
import { testProductionAcceptanceContract } from "./productionAcceptanceContract.test.js";
import { testLlmPlannerFailClosed } from "./llmPlanner.test.js";
import { testEvidenceQuality } from "./evidenceQuality.test.js";

async function main() {
  await testConnectorEnvelope();
  await testProjectDetectionWizard();
  await testDiscoveryScanDrafts();
  await testGovernanceSecurityBot();
  testCiContract();
  await testCiGatePolicy();
  await testCiCliErrorReports();
  await testCiShellExitContract();
  await testProjectAdapter();
  await testExternalProjectSmoke();
  await testInvestmentAgentWorkflowExternalSmoke();
  await testBenchmarkContract();
  await testProductionAcceptanceContract();
  await testLlmPlannerFailClosed();
  testEvidenceQuality();
  testBenchmarkEvaluation();
  await testIndependentFixtures();
  testRepairProposals();
  await testRunEventStore();
  testRetryPolicy();
  testGithubChecks();
  await testCodeImpactGraph();
  testMissionPreview();
  testRunnerLifecyclePolicy();
  testRunnerExecutablePlanBinding();
  await testScenarioDraftLifecycle();
  testScenarioParser();
  testPlanStepSchema();
  testJudgeSchema();
  testReportRendererRedaction();
  await testSecurityBoundaries();
  await testRunHistoryComparison();
  await testRunLockGovernance();
  await testReportsRetention();
  testRunRequestContract();
  await testArtifactIntegrity();
  await testLocalConfigInit();
  await testServiceHealthContract();
  await testRunBundleArchive();
  await import("../src/selfTest.js");
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
